spring:
  application:
    name: battleship
  datasource:
    url: jdbc:h2:mem:olympic-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  security:
    authentication:
      basic:
        disableCSRF: true
        user: admin
        password: admin

h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false
      web-allow-others: false